name: build
on: 
  push: 
    paths:
      - '**.js'
jobs: 
  build:
    runs-on: ${{matrix.os}}
   strategy:
     matrix:
       os: [macos-laatest, windows-latest, ubuntu-lastest]
       node: [10,12,14]
       exclude:
         - os: macos-lastes
           node: 10
   steps:
     - uses: actions/checkout@v2
     - name: Use node.js ${{matirx.node}}
       uses: actions/setup-node@v1
       with:
         node-version: ${{matrix.node}}
     -  run: npm ci
     - mpm run buils --if-present
    
